FROM ubuntu

RUN apt-get update && apt-get install -y openssh-server &&  rm -rf /var/lib/apt/lists/*  && \
    sed -i "s/#AuthorizedKeysFile/AuthorizedKeysFile/g" /etc/ssh/sshd_config && \
    /etc/init.d/ssh start

