FROM ubuntu


RUN apt-get update && \
    apt-get install -y openssh-server && \
    sed -i "s/#AuthorizedKeysFile/AuthorizedKeysFile/g" /etc/ssh/sshd_config && \
    /etc/init.d/ssh start  && \

    apt-get install -y wget && \
    
    wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F;oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/8u77-b03/jdk-8u77-linux-x64.tar.gz" -P / && \
    
    mkdir /usr/lib/jvm && \
    tar zxvf /jdk-8u77-linux-x64.tar.gz -C /usr/lib/ && \
    mv /usr/lib/jdk1.8.0_77 /usr/lib/jvm/jdk8 && \
    rm /jdk-8u77-linux-x64.tar.gz && \
    
    rm -rf /var/lib/apt/lists/*


ENV JAVA_HOME="/usr/lib/jvm/jdk8" \
    JRE_HOME="${JAVA_HOME}/jre" \
    CLASSPATH=".:${JAVA_HOME}/lib:${JRE_HOME}/lib"
ENV PATH ${PATH}:${JAVA_HOME}/bin


